### ISSUE TITLE
Webpack dev server with hot reloading

### ISSUE THREAD

**Issue by hizo** [nearform/react-pwa#80]
Explore the possibility to use webpack dev server with hot reloading.

**Comment by hizo** [comment]
Spent several hours on this. It's a pain to set up. Couldn't get hot reloading to work in the end, which was the whole purpose of this. Even if I could get this to work, setup for this adds a huge overhead compared to our current setup. Not worth the effort.

**Comment by hizo** [comment]
To be solved by https://github.com/nearform/react-pwa/issues/82

**Comment by salmanm** [comment]
Sorry I don't have the full context; I've done something similar in bolt project last week. HMR with SSR. Its working great so far. We can chat if it's helpful.

**Comment by hizo** [comment]
That would be nice! I am in GMT+1 time zone. When does it suit you tomorrow?

**Comment by hizo** [comment]
Doesn't work for me today. Let's try Monday 11:30 my time?

**Comment by salmanm** [comment]
Sure
